// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkRYjv0izcTulI-k5GyQZB61sGDAkcM_Q',
    appId: '1:24868641823:web:c9ee03ed83017faa9c492a',
    messagingSenderId: '24868641823',
    projectId: 'sanad-ac037',
    authDomain: 'sanad-ac037.firebaseapp.com',
    storageBucket: 'sanad-ac037.appspot.com',
    measurementId: 'G-51KKBSCEWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHsrcYbgmTGnF-m9zULKm0FiI_HZnxMp0',
    appId: '1:24868641823:android:1660950d5e412fb59c492a',
    messagingSenderId: '24868641823',
    projectId: 'sanad-ac037',
    storageBucket: 'sanad-ac037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWjOMe8_RYT0sQhHN0JTtVEPFvEx-Vmqc',
    appId: '1:24868641823:ios:fa7e700b543170789c492a',
    messagingSenderId: '24868641823',
    projectId: 'sanad-ac037',
    storageBucket: 'sanad-ac037.appspot.com',
    iosBundleId: 'com.sanad.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWjOMe8_RYT0sQhHN0JTtVEPFvEx-Vmqc',
    appId: '1:24868641823:ios:a88d1d3c4384701f9c492a',
    messagingSenderId: '24868641823',
    projectId: 'sanad-ac037',
    storageBucket: 'sanad-ac037.appspot.com',
    iosBundleId: 'com.example.templete.RunnerTests',
  );
}
