-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDBnntgjDKdYjY/m1
gk2P2MIsJ0E60hSJHkK6F3r7uhagCgYIKoZIzj0DAQehRANCAASeqlyNoYBAncDC
5ozbOnZLXdj3PBA7XMWfZQK/nK5uHZuK0JVSxqZ7HYKaU3zt7rb2hxzoSht6wcrS
xBRCoAaY
-----END PRIVATE KEY-----